### ISSUE TITLE
[Feat] Cafe Search

### ISSUE THREAD

**Issue by dlrlfgh1210** [CaZaIt/CaZaIt-Android#102]
- [ ] 카페 서치할 때 굳이 돋보기 누르지 않더라도 검색 할 수 있도록 하기
- [ ] 예를 들어 제주몰빵 검색할 시에 검색한 내용이 제대로 로그값에 찍히도록 하기

**Comment by YiBeomSeok** [comment]
단계별로 어려운 게 있으면 바로 알려주세요

**Comment by YiBeomSeok** [comment]
이슈에 브렌치 연결 해주세요

**Comment by YiBeomSeok** [comment]
수요일 밤까지 작업 끝내지 못할 경우
목요일 낮까지 그림으로 계획 구조도를 그려서 보여 주세요
같이 의논해봅시다
