### ISSUE TITLE
[Fix] Map Error

### ISSUE THREAD

**Issue by WooBinHam** [CaZaIt/CaZaIt-Android#115]
- [ ] 지도에서 현재 위치 버튼 눌렀을 때에 튕기는 현상 수정

**Comment by WooBinHam** [comment]
## 추가
- ViewPage에 Glide를 이용하여 이미지 추가
- 메뉴에 이미지 추가

**Comment by YiBeomSeok** [comment]
- [ ] 지도에서 현재 위치 버튼을 눌렀을 때 앱이 비정상적으로 종료되는 문제 해결
