### ISSUE TITLE
[Feat] RatingReview Frag Context Menu

### ISSUE THREAD

**Issue by WooBinHam** [CaZaIt/CaZaIt-Android#37]
## [Feat] RatingReview Frag Context Menu
- [ ] 리뷰 정렬 기준 선택하는 것 구현하기

**Comment by WooBinHam** [comment]
## 고민 중
1. 일단 정렬 기준 선택은 뺄 예정이랬음
2. 일단 dialog로 기능 구현만 해 놓음
3. context menu로 할지 말지 모름

**Comment by YiBeomSeok** [comment]
Adapter 관련한 코드들 수정
